import React from "react";
import { View, StyleSheet, Text, Pressable, ScrollView,  } from "react-native";


export default function Popup(props) {
    var verdict = '';
    switch (props.results['label']){
        case 0:
            verdict = " AI Text "
            break;
        case 1:
            verdict = " Human Text "    
            break;
        case 5:
            verdict = "The Text could contain parts generated by AI. (requires more text for better judgement)"
            break;
        default:
            verdict = "oops"


    }
    return (
        <View style={{ flex: 1, justifyContent: 'flex-end' }}>

            <View style={styles.content}>
                <View style={styles.block}>
                    <View style={styles.textBlock}>
                    <Text style={styles.hText}> {verdict} </Text>
                    </View>
                </View>
                <ScrollView>
                    <Text style={styles.bText}>
                        {props.results['text']}
                    </Text>
                </ScrollView>
            </View>
        </View>
    )
}


const styles = StyleSheet.create({

    content: {
        backgroundColor: '#222222',
        height: 600,
        justifyContent: 'center',
        position: 'relative',
        bottom: 50,
        margin: 10,
        padding: 20,
        borderRadius: 30,


    },
    hText: {
        fontSize: 45,
        color: '#aaaaaa'
    },
    bText: {
        fontSize: 20
        ,
        color: '#dddddd'
    },
    block: {
        marginVertical:100,
        width: '100%',
        
    },
    textBlock:{
        position: 'relative',
        margin: 20,
        alignItems: 'center',
    }

})